version: '2'
services:
    kismet-build:
        build: .

        environment:
            - CHECKOUT=HEAD
            - VERSION

        command: /scripts/build_hirsute.sh

        tmpfs: 
            - /build:exec,mode=777

        volumes:
            - /home/dragorn/src/kismet-packaging/dpkgs-hirsute:/dpkgs
            - /home/dragorn/src/kismet-packaging/scripts:/scripts:ro
            - /home/dragorn/src/kismet:/kismet:ro
