version: '2'
services:
    kismet-build:
        build: .
        
        environment:
            - CHECKOUT=HEAD
            - VERSION
            - ARCH=armhf
            - ABI=arm-linux-gnueabihf

        command: /scripts/launch/ubuntu_focal.sh

        tmpfs: 
            - /build:exec,mode=777

        volumes:
            - ${BASE_DIR}/dpkgs-focal:/dpkgs
            - ${BASE_DIR}/scripts:/scripts:ro
            - ${SRC_DIR}:/kismet:ro
