version: '2'
services:
    kismet-build:
        build: .

        environment:
            - CHECKOUT=HEAD
            - VERSION
            - ARCH=i386
            - ABI=i386-linux-gnu

        command: /scripts/launch/debian_bullseye.sh

        tmpfs: 
            - /build:exec,mode=777

        volumes:
            - ${BASE_DIR}/dpkgs-bullseye:/dpkgs
            - ${BASE_DIR}/scripts:/scripts:ro
            - ${SRC_DIR}:/kismet:ro
