version: '2'
services:
    kismet-build:
        build: .

        environment:
            - CHECKOUT=HEAD
            - VERSION
            - ARCH=arm64
            - ABI=aarch64-linux-gnu

        command: /scripts/launch/ubuntu_impish.sh

        tmpfs: 
            - /build:exec,mode=777

        volumes:
            - ${BASE_DIR}/dpkgs-impish:/dpkgs
            - ${BASE_DIR}/scripts:/scripts:ro
            - ${SRC_DIR}:/kismet:ro

    shell:
      build: .
      command: /bin/sh
